### ISSUE TITLE
Renaming pyment

### ISSUE THREAD

**Issue by dadadel** [meyt/payit#1]
Hi @meyt,

You have chosen the same project name than the [Pyment](https://github.com/dadadel/pyment) project relating to docstrings management. It is a pitty you didn't noticed that it was already widely used. Note that this project can interest you as it is intended for Python developers.

BTW,  [Pyment](https://github.com/dadadel/pyment) is now 4 years old and counts many users.
Work is done to integrate it to Debian (see [issue](https://github.com/dadadel/pyment/issues/45)) and it is in progress to be added to Pypi soon as you can see in [pypi](https://testpypi.python.org/pypi?:action=display&name=Pyment&version=0.3.2.dev3) and in that [issue](https://github.com/dadadel/pyment/pull/41).

However, we noticed that you created a Pypi project with _pyment_ name few days ago. That is very confusing for the numerous Pyment users!
As your project is very young and not yet known, having no users, I would like to know if you could change its name, or at least remove it from Pypi. If you keep the same name and in the futur it become famous and if our project become confusing for most of users we will then remove it from Pypi and rename it, as today it is the case concerning your project.

So please consider letting us use _Pyment_ name in Pypi.

Best regards,

Adel

**Comment by meyt** [comment]
Wow, 4 years is too late dude! however it's not my business, so as respect to all users that use [dadadel/pyment](https://github.com/dadadel/pyment) i will change my project name completly, also i redirecting domain (pyment.ir) to [dadadel/pyment](https://github.com/dadadel/pyment) until that expires. :wine_glass:

**Comment by meyt** [comment]
Packages removed and, `asettouf` user on pypi is now have owner role.

**Comment by dadadel** [comment]
Thank you @meyt,
That's very nice. I hope your project will work as you want.
Good luck.
Cheers,
Adel

**Comment by dadadel** [comment]
Hi @meyt,
I come back again concerning the Pyment permissions on Pypi.
You have granted to asettouf the maintainer role.
But we still not have owner role.
Could you please provide to my user (https://pypi.org/user/dadel/) the owner role on Pyment?
Thank you.
Best
Adel

**Comment by meyt** [comment]
Done 
![image](https://user-images.githubusercontent.com/10482278/43363053-a042521a-9310-11e8-9fbd-36b8b45df1c1.png)
